### ISSUE TITLE
Not using TypeScript, getting a warning from a peer dependency requiring typescript

### ISSUE THREAD

**Issue by tagliala** [neostandard/neostandard#181]
Hello,

I'm not a JavaScript developer.

I'm preparing to migrate from standard to neostandard. 

I want to report that I'm getting this warning:

```
$ yarn
yarn install v1.22.22
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "neostandard > typescript-eslint > @typescript-eslint/eslint-plugin > ts-api-utils@1.3.0" has unmet peer dependency "typescript@>=4.2.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 4.08s.
```

My project does not use typescript, is this warning somehow avoidable?

https://github.com/neostandard/neostandard/blob/7ec0e86207a6ae735a0440bd8f706d8d739f53b3/package.json#L90

Readme ref: https://github.com/neostandard/neostandard?tab=readme-ov-file#exported-plugins

I do not quite full understand if this is mandatory

**Comment by voxpelli** [comment]
You can safely ignore it, it's only needed if you activate the typescript linting

Not sure if we could make it go away, it's far down in the dependency tree

I'll leave this open and if I get time some day I may dig into it as it for sure is annoying

**Comment by tagliala** [comment]
Thanks.

I've also some concerns related to the "runtime" dependency on react. 

I'm migrating from standard to neostandsard and I've seen +300 lines in the yarn.lock related to react, which is not being used by the project. Sorry I'm not a JavaScript developer, so I'm asking if typescript and react can be added to peer dependencies or explicitly added in case you need them 

Migration commit (WIP): https://github.com/diowa/ruby3-rails7-bootstrap-heroku/pull/975

**Comment by voxpelli** [comment]
> the "runtime" dependency on react

What?! This makes me quite upset as well. This really has no place here. I wonder why it's included 🤔

I know some CLI tools are using https://github.com/vadimdemedes/ink which in turn uses React, but none in this dependency chain should unless ESLint has started to use it

I'm a bit burnt out after a week with battles in OSS and elsewhere so I will not be able to look into this now and I'm a bit behind on my work project due to the same so it will take a while to get time, but maybe eg @jerome-benoit has some time to dig into it

**Comment by jerome-benoit** [comment]
> > the "runtime" dependency on react
> 
> What?! This makes me quite upset as well. This really has no place here. I wonder why it's included 🤔

The content of the yarn.lock shows nothing inappropriate relative to `eslint-plugin-react`

```
eslint-plugin-react@^7.36.1:
  version "7.37.1"
  resolved "https://registry.yarnpkg.com/eslint-plugin-react/-/eslint-plugin-react-7.37.1.tgz#56493d7d69174d0d828bc83afeffe96903fdadbd"
  integrity sha512-xwTnwDqzbDRA8uJ7BMxPs/EXRB3i8ZfnOIp8BsxEQkT0nHPp+WWceqGgo6rKb9ctNi8GJLDT4Go5HAWELa/WMg==
  dependencies:
    array-includes "^3.1.8"
    array.prototype.findlast "^1.2.5"
    array.prototype.flatmap "^1.3.2"
    array.prototype.tosorted "^1.1.4"
    doctrine "^2.1.0"
    es-iterator-helpers "^1.0.19"
    estraverse "^5.3.0"
    hasown "^2.0.2"
    jsx-ast-utils "^2.4.1 || ^3.0.0"
    minimatch "^3.1.2"
    object.entries "^1.1.8"
    object.fromentries "^2.0.8"
    object.values "^1.2.0"
    prop-types "^15.8.1"
    resolve "^2.0.0-next.5"
    semver "^6.3.1"
    string.prototype.matchall "^4.0.11"
    string.prototype.repeat "^1.0.0"
```

Which are for most of them very small and common deps.

Since the goal of neostandard is to cover in a unique package all the standard rules set, it relies inevitably on a lot of tooling. You can't have a linting setup supporting a wide range of JS flavors without a bunch of deps in the current state of the JS ecosystem. `biome` is promising but it's still far from being functionally equivalent to eslint in term of linting ... 

Maybe we can investigate on a way to make `eslint-plugin-react` an optional peer dependency with some warnings in case one needs jsx support in its code base. 
For `typescript-eslint`, I do not see the gain of trying to make an optional peer deps but I do see the pain (probably huge) at trying to do it given its transversal usage by eslint styling plugin, and the more relative pain for user trying to setup neostandard on a TS code base. 

Given the current issues backlog, I would rather do a PR to integrate eslint-plugin-import when time permits than trying to untangle some deps in neostandard ...

**Comment by voxpelli** [comment]
Oh, eslint-plugin-react is fine as long as it doesn't pull in the entire react itself :)

**Comment by jerome-benoit** [comment]
> Oh, eslint-plugin-react is fine as long as it doesn't pull in the entire react itself :)

jsx-ast-utils could? I do not think so.

**Comment by tagliala** [comment]
Thanks for your thorough answers, I now have a better understanding of the choices made for neostandard

**Comment by bcomnes** [comment]
Also just for additional context: if you are able, it's generally advisable to migrate off yarn 1. yarn 4 is quite a departure from yarn 1 in terms of design, so switching to npm 10 would probably be the simplest path. pnpm is also a modern, 3rd party  option. Here is a colorful rant with more context about permanent bugs that won't be fixed in yarn 1: https://github.com/eslint/eslint/discussions/17215#discussioncomment-8042361

**Comment by tagliala** [comment]
>  it's generally advisable to migrate off yarn 1. 

Done, switched to npm, thanks for the suggestion

**Comment by voxpelli** [comment]
Closing as answered 🙂
